apiVersion: v1
kind: Service
metadata:
  name: nginx-fe-proxy-svc
spec:
  type: LoadBalancer
  selector:
    run: passthrough
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
